version: '3.9'
services:

  tracing-collector:
    image: otel/opentelemetry-collector
    ports:
      - "55680:55680"  # OTLP gRPC port
    volumes:
      - ./etc/collector-config.yaml:/etc/otel/collector-config.yaml
    networks:
      - sp-network

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686 # serve frontend
    networks:
      - sp-network

  gateway:
    build:
      context: ./src/gateway
    container_name: gateway
    ports:
      - 8080:8080
    environment: 
      PORT: "8080"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalog-service:3550"
      CART_SERVICE_ADDR: "cart-service:3551"
      SHIPPING_SERVICE_ADDR: "shipping-service:3552"
      CHECKOUT_SERVICE_ADDR: "checkout-service:3553"
    env_file:
      - ./etc/tracing-vars.env
    networks:
      - sp-network

  redis-cart:
    image: redis:alpine
    container_name: redis-cart
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      - sp-network

  postgres:
    image: postgres:15-alpine
    container_name: sp-microservices-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
    volumes:
      - ./.data/postgras:/var/lib/postgresql/data
    networks:
      - sp-network

  productcatalog-service:
    build:
      context: ./src/productcatalogservice
    container_name: productcatalog-service
    ports:
      - 3550:3550
    environment:
      PORT: 3550
      DB_HOST: postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    env_file:
      - ./etc/tracing-vars.env
    depends_on:
      - postgres
    networks:
      - sp-network

  cart-service:
    build:
      context: ./src/cartservice/src
    container_name: cart-service
    ports:
      - 3551:3551
    environment:
      PORT: 3551
      REDIS_ADDR: redis-cart:6379
    depends_on:
      - redis-cart
    networks:
      - sp-network

  shipping-service:
    build:
      context: ./src/shippingservice
    container_name: shipping-service
    ports:
      - 3552:3552
    environment:
      PORT: 3552
    env_file:
      - ./etc/tracing-vars.env
    networks:
      - sp-network

  checkout-service:
    build:
      context: ./src/checkoutservice
    container_name: checkout-service
    ports:
      - 3553:3553
    environment:
      PORT: "3553"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalog-service:3550"
      CART_SERVICE_ADDR: "cart-service:3551"
      SHIPPING_SERVICE_ADDR: "shipping-service:3552"
      PAYMENT_SERVICE_ADDR: "payment-service:3554"
    env_file:
      - ./etc/tracing-vars.env
    networks:
      - sp-network

  payment-service:
    build:
      context: ./src/paymentservice
    container_name: payment-service
    ports:
      - 3554:3554
    environment:
      PORT: 3554
      NATS_URL: nats://localhost:4222
    env_file:
      - ./etc/tracing-vars.env
    networks:
      - sp-network

networks:
  sp-network:
    driver: bridge

#  postgres:
#    image: postgres:15-alpine
#    container_name: postgres-product-ordering-system
#    ports:
#      - 5432:5432
#    environment:
#    - POSTGRES_PASSWORD=postgres
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 60s
#      timeout: 10s
#      retries: 3
#      start_period: 15s
#    volumes:
#      - ./.data/postgras:/var/lib/postgresql/data
#
#  nats:
#    container_name: nats-js
#    image: nats:2.9-alpine
#    ports:
#      - "4222:4222"
#    command: "-js --sd /data --http_port 8222"
#    volumes:
#      - ./.data/nats:/data
